spring:
  datasource:
    name: db
    username: root
    password: root
    url: jdbc:h2:mem:db 
  h2:
    console:
       enabled: true
  jpa:
     hibernate.ddl-auto: none
     open-in-view: false
eureka:
  client:
     service-url:
       defaultZone: http://localhost:8761/eureka/
